[wip] Chainbridge wizard
ChainSafe/chainbridge-deploy pull request #21
Opened 2020-10-04 01:46 UTC by GregTheGreek

This PR adds a interactive shell for interacting with chainbridge.

2020-10-05 12:52 UTC, ansermino requested changes
Can we show defaults for options?

2020-10-05 12:52 UTC, ansermino commented on cb-sol-cli/wizard/questions/deploy.js
> +            validate: x => x <= 0 ? "Number must be greater than 0" : true
Should allow it to be 0

2020-10-05 12:52 UTC, ansermino commented on cb-sol-cli/wizard/questions/deploy.js
> +            validate: x => x <= 0 ? "Number must be greater than 0" : true
Forces integers so min is 1eth

2020-10-05 12:52 UTC, ansermino commented on cb-sol-cli/wizard/questions/deploy.js
> +                message: "What threshold do you want? (number)"
```suggestion
                message: "What vote threshold do you want? (number)"
```

2020-10-05 12:52 UTC, ansermino commented on cb-sol-cli/wizard/questions/deploy.js
> +                message: "How many relayers do you want? (number)",
Saying "number" seems redundant

2020-10-05 12:52 UTC, ansermino commented on cb-sol-cli/wizard/questions/deploy.js
> +    }
```
? Enter relayer addresses (Comma separated values) ›  0xff93B45308FD417dF303D6515aB04D9e89a750Ca,0x8e0a907331554AF72563Bd8D43051C2E64Be5d35,0x24962717f8fA5BA3b931bACaF9ac03924EB475a0
›  0xff93B45308FD417dF303D6515aB04D9e89a750Ca is not a valid Ethereum address!

```

2020-10-05 15:55 UTC, GregTheGreek commented on cb-sol-cli/wizard/questions/deploy.js
> +    }
Cannot reproduce

2020-10-08 20:36 UTC, ansermino commented on cb-sol-cli/wizard/questions/deploy.js
> +            validate: x => x <= 0 ? "Number must be greater than 0" : true
Still forces integer

2020-10-08 20:36 UTC, ansermino commented on cb-sol-cli/wizard/questions/deploy.js
> +    }
```
? Enter relayer addresses (Comma separated values) › "0xf78b3E93d744e233594A797A00f87451cd236E53,0x89A183Cd4679Ba3195D3f93a105c643c9075aC97,0x4a0c39336b2e0976EA50Da6C992E672e87546e7B"
› "0xf78b3E93d744e233594A797A00f87451cd236E53 is not a valid Ethereum address!
```

2022-07-12 14:38 UTC, closed without merging