Add detailed erc20
ChainSafe/chainbridge-deploy pull request #40
Opened 2021-01-28 15:14 UTC by GregTheGreek

This PR changes the behaviour of the erc20 contact. 

Previous erc20 contracts were deployable with the `name` and `symbol` parameter. This PR extends the previous contract to allow a third argument `decimal`.

2021-01-28 15:29 UTC, lastperson requested changes
Typos. Otherwise I like it!

2021-01-28 15:29 UTC, lastperson commented on cb-sol-cli/cmd/deploy.js
> +    .option('--erc20Decimal <amoutn>', 'Decimal for erc20 contract', 18)
```suggestion
    .option('--erc20Decimals <amount>', 'Decimals for erc20 contract', 18)
```

2021-01-28 15:29 UTC, lastperson commented on cb-sol-cli/cmd/deploy.js
> +    const contract = await factory.deploy(args.erc20Name, args.erc20Symbol, args.erc20Decimal, { gasPrice: args.gasPrice, gasLimit: args.gasLimit});
```suggestion
    const contract = await factory.deploy(args.erc20Name, args.erc20Symbol, args.erc20Decimals, { gasPrice: args.gasPrice, gasLimit: args.gasLimit});
```

2021-01-29 13:40 UTC, ansermino commented
We already get a lot of questions about where the ERC20 contract comes from (since it's currently imported from NPM). We should include source here not just ABI.

2021-01-29 14:21 UTC, GregTheGreek commented
@ansermino updated.

2021-06-08 18:02 UTC, vezenovm submitted a review, later dismissed
Tests passing now

2021-06-08 18:11 UTC, lastperson approved these changes

2021-06-08 18:16 UTC, merged